Repository AGH-Narzedzia-Informatyczne-2023-2024/Portal2d, pull requests merged in 2023-11, with the labels that each got.

#12 stworzyłem główną pętle
  main.py
Labels: Important

#14 dodanie symulacji
  simulation.py
Labels: help wanted

#17 Dodanie pliku playera
  player.py
Labels: enhancement, opcjonalne

#15 dodanie menu
  menu.py
Labels: Important

#16 Entities
  entities.py
Labels: Important

#13 level.py
  level.py
Labels: Important

#18 Level
  level.py
Labels: good first issue
